spring.application.name=redis-cache

spring.datasource.url=jdbc:mysql://localhost:3308/redis_cache
spring.datasource.username=root
spring.datasource.password=root123

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.data.redis.port=6379
spring.data.redis.host=localhost
#spring.data.redis.username=
#spring.data.redis.password=
spring.cache.type=redis